DROP TABLE OWNER;
DROP TABLE TEAM;
DROP TABLE PLAYER;
DROP TABLE MEMBERS;

CREATE SEQUENCE MEMBERS_SEQ;
CREATE SEQUENCE PLAYER_SEQ;
CREATE SEQUENCE TEAM_seq;

CREATE TABLE TEAM(
    T_NO NUMBER(5) CONSTRAINT T_PK PRIMARY KEY,
    C_TEAMNAME VARCHAR2(20) NOT NULL
);

CREATE TABLE MEMBERS(
    M_NO NUMBER(5) CONSTRAINT M_PK PRIMARY KEY,
    T_NO NUMBER(5) CONSTRAINT M_T_FK REFERENCES TEAM (T_NO) ON DELETE SET NULL,
    EMAIL_ID VARCHAR2(20) CONSTRAINT M_UK UNIQUE NOT NULL,
    PW VARCHAR2(20) NOT NULL,
    BALANCE NUMBER(20) DEFAULT 10000000000 CHECK(BALANCE > 0),
    IS_ADMIN NUMBER(1) DEFAULT 0 CHECK(IS_ADMIN IN(0,1)) NOT NULL
);

CREATE TABLE PLAYER(
    P_NO NUMBER(5)CONSTRAINT P_PK PRIMARY KEY,
    T_NO NUMBER(5) CONSTRAINT P_T_FK REFERENCES TEAM (T_NO) ON DELETE SET NULL,
    NAME VARCHAR2(20) NOT NULL,
    BACK_NUM NUMBER(2) NOT NULL,
    SHOT NUMBER(2) NOT NULL,
    PASS NUMBER(2) NOT NULL,
    DAFENSE NUMBER(2) NOT NULL,
    POSITION VARCHAR2(2) NOT NULL
);

CREATE TABLE OWNER(
    M_NO NUMBER(5) CONSTRAINT OWNER_M_NO_fk REFERENCES MEMBERS(M_NO) ON DELETE CASCADE NOT NULL,
    P_NO NUMBER(5) CONSTRAINT OWNER_P_NO_fk REFERENCES PLAYER(P_NO) ON DELETE CASCADE NOT NULL
);

INSERT INTO PLAYER VALUES(PLAYER_SEQ.naxtval,'MESSI',30,99,99,40,'FW');